version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-audit
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: audit_db
    volumes:
      - mongodb_data:/data/db
      - ./backend/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - audit-network

volumes:
  mongodb_data:
    driver: local

networks:
  audit-network:
    driver: bridge 