export const staticAnswers: { [key: string]: string } = {
  // Utilisateurs / Sessions
  "Quels sont les utilisateurs qui ont le plus de sessions ouvertes ?": "Utilisateurs détectés : SYS, SYSTEM, CDB$ROOT, PDB$SEED, SMART2DTESTPDB",
  "Quel utilisateur a généré le plus d’audits ?": "Utilisateur le plus actif : SYS (nombre élevé d'exécutions et lectures)",
  "Combien de sessions ont été ouvertes par `SYS` ?": "Sessions de SYSTEM : limitées, pas en activité principale",
  "Quels utilisateurs ont accédé à la base aujourd’hui ?": "Accès récents à la base : uniquement SYS sur le container root",
  "Quels sont les terminaux utilisés par chaque utilisateur ?": "Terminal principal utilisé : smart2d.smart2dservices.com (Linux x86 64-bit)",
  "Quel utilisateur a exécuté le plus d’instructions `SELECT` ?": "Requêtes SELECT dominantes : plus de 253 000 exécutions",
  "Quels utilisateurs ont eu des accès depuis des IP externes ?": "Aucun accès depuis IP externe enregistré dans ce rapport",
  "L’utilisateur `SYSTEM` a-t-il modifié des tables ?": "Sessions de SYSTEM : limitées, pas en activité principale",
  "Y a-t-il eu des connexions anonymes ?": "Aucune connexion anonyme détectée",
  "Quels utilisateurs ont accédé à plusieurs bases ?": "Pas d’accès à plusieurs bases depuis un même utilisateur (un seul PDB actif)",

  // Types d’opérations
  "Combien d'opérations `INSERT` ont été effectuées ?": "INSERT/UPDATE/DELETE : non explicitement listés mais activité principalement en lecture",
  "Quelle est la distribution des opérations `SELECT`, `UPDATE`, `DELETE` ?": "Distribution SELECT vs autres : très majoritairement des SELECT",
  "Quelles tables ont été mises à jour récemment ?": "Tables modifiées : aucune modification directe listée dans AWR",
  "Quelles opérations ont été faites sur la table `AUDIT_TRAIL` ?": "Table AUDIT_TRAIL : aucune mention d’accès direct",
  "Les `DROP TABLE` sont-ils fréquents ?": "Opérations DROP : aucune détectée",
  "Quels objets ont été créés récemment ?": "Objets créés : non listés dans ce snapshot",
  "Y a-t-il des accès à des vues système sensibles ?": "Accès aux vues système : oui, ex : SYS.VIEW$",
  "Des utilisateurs ont-ils tenté des `GRANT` ?": "GRANT ou REVOKE : aucune instruction détectée",
  "Quelles fonctions système ont été invoquées ?": "Appels système : plusieurs procédures PL/SQL exécutées (DBMS_WORKLOAD_REPOSITORY)",
  "Combien d’opérations DDL ont été détectées ?": "DDL exécutées : non détectées dans l’AWR analysé",

  // Activité temporelle
  "À quelle heure observe-t-on le pic d'activité ?": "Pic d'activité : autour de 02:00 – 02:30 du 24 juillet 2025",
  "Quels jours de la semaine sont les plus actifs ?": "Jour le plus actif : 24 juillet 2025 (unique jour du snapshot)",
  "L'activité est-elle plus élevée le week-end ?": "Aucune activité week-end (non couvert dans la période AWR)",
  "Quelle session a duré le plus longtemps ?": "Session la plus longue : non mesurable précisément mais toutes dans un intervalle de 4h",
  "Quelles opérations ont été effectuées après 20h ?": "Activité après 20h : non (logs de 01:00 à 05:00)",
  "Quelle est la moyenne d’événements par heure ?": "Moyenne événements/h : ~63,347 requêtes exécutées par heure",
  "Quels utilisateurs travaillent de nuit ?": "Utilisateurs de nuit : SYS uniquement",
  "A-t-on eu des actions à des heures inhabituelles ?": "Aucune activité 'inhabituelle' détectée dans la période",
  "Les logs montrent-ils une augmentation soudaine d’activité ?": "Pas de pics soudains extrêmes dans l'activité",
  "L’activité diminue-t-elle durant les jours fériés ?": "Pas de corrélation avec jours fériés (1 jour seulement analysé)",

  // Objets manipulés
  "Quelle table est la plus consultée ?": "Table la plus consultée : non nommée, mais vues système utilisées",
  "Quelles vues ont été accédées récemment ?": "Accès à des vues : oui (SYS.VIEW$)",
  "Y a-t-il eu des suppressions d’index ?": "Suppression d’index : aucune",
  "Quels objets ont été renommés ?": "Renommage d’objets : aucun",
  "La table `USERS` a-t-elle été modifiée ?": "Table USERS : non mentionnée explicitement",
  "Quels objets ont été exportés ?": "Export d’objets : aucune trace dans le snapshot",
  "Y a-t-il eu des accès à `DBA_USERS` ?": "Accès à DBA_USERS : non détecté",
  "Des objets ont-ils été supprimés sans recréation ?": "Objets supprimés sans recréation : non détecté",
  "Quelles tablespaces ont été utilisées ?": "Tablespaces utilisés : non listés",
  "Quels objets ont été consultés en lecture seule ?": "Objets consultés en lecture seule : essentiellement des vues système",

  // Sécurité et droits
  "Quels rôles ont été modifiés ?": "Modifications de rôle : aucune",
  "Des utilisateurs ont-ils changé leur mot de passe ?": "Changement de mot de passe : non détecté",
  "Y a-t-il eu des tentatives de connexion échouées ?": "Tentatives de connexion échouées : 0 logon failure",
  "Quels privilèges ont été accordés ou révoqués ?": "Privilèges accordés/révokés : aucun GRANT/REVOKE",
  "Des utilisateurs ont-ils obtenu le rôle DBA ?": "Aucune élévation de privilèges (ex : rôle DBA) détectée",
  "Quelles politiques d’audit sont actives ?": "Politiques d’audit : non visibles dans ce AWR",
  "Y a-t-il eu des accès non autorisés ?": "Aucun accès non autorisé détecté",
  "Des audits ont-ils été désactivés ?": "Désactivation de l’audit : non détectée",
  "A-t-on détecté des actions suspectes ?": "Aucune activité suspecte relevée",
  "Quel utilisateur a modifié les politiques d’audit ?": "Modification de politiques d’audit : non détectée",

  // Événements système
  "Quelles erreurs ORA- ont été enregistrées ?": "Erreurs ORA- : aucune rapportée",
  "Des processus système ont-ils échoué ?": "Processus système : CKPT, DBW0, PSP0 actifs",
  "A-t-on eu des erreurs de tablespace ?": "Erreur tablespace : aucune",
  "Y a-t-il eu des redémarrages de la base ?": "Redémarrage base : non (uptime stable)",
  "Les logs montrent-ils des blocages ?": "Blocages (locks) : non visibles",
  "Des requêtes ont-elles dépassé le temps d'exécution prévu ?": "Requêtes longues : pas de requêtes lentes listées",
  "Quel est le taux de `Hard Parse` ?": "Hard Parse rate : 0.2/sec (faible, bon)",
  "Quelle est la latence moyenne de lecture ?": "Latence moyenne lecture : 289.92 μs",
  "Combien de requêtes ont échoué ?": "Requêtes échouées : non listées",
  "A-t-on détecté des verrous ?": "Verrous : aucune activité de verrou significative détectée",

  // Performance
  "Quel est le temps moyen d’exécution d’une requête ?": "Temps moyen exécution requête : non listé directement",
  "Quels sont les événements d’attente les plus fréquents ?": "Événements d’attente dominants : control file parallel write, CPU, db file async I/O",
  "Quelle est l’utilisation CPU par session ?": "Utilisation CPU par session : faible",
  "Combien de lectures physiques par seconde ?": "Lectures physiques/sec : environ 0.3/sec",
  "Quelle est l’utilisation mémoire (SGA/PGA) moyenne ?": "Utilisation mémoire : PGA ~556 Mo, SGA ~1.6 Go",
  "Quelle est la taille des tablespaces ?": "Tablespaces volumineux : non listés",
  "Quelle est la table la plus volumineuse ?": "Table la plus grosse : non mesurée",
  "Y a-t-il une contention sur les verrous ?": "Contention verrous : absente",
  "Quelles requêtes sont les plus longues ?": "Requêtes les plus longues : AWR_REPORT (3.13% activité)",
  "Le cache buffer est-il efficace ?": "Cache efficace : oui, 99.77% hit ratio",

  // Connexions / Hôtes
  "Quelles adresses IP se sont connectées ?": "Adresses IP : non listées",
  "Depuis quels terminaux a-t-on accédé à la base ?": "Terminaux : smart2d.smart2dservices.com",
  "Quels OS sont utilisés par les clients ?": "OS client : Linux 64-bit",
  "Y a-t-il des connexions suspectes depuis l’extérieur ?": "Connexions externes : aucune",
  "Combien de connexions proviennent de `LAPOSTE\\PC-ATCHEMI` ?": "Activité sur LAPOSTE\\PC-ATCHEMI : non présente dans ce fichier",
  "Quels serveurs exécutent `sqlplus` ?": "Programmes Oracle : sqlplus, oracle@...",
  "Les connexions sont-elles réparties sur plusieurs nœuds ?": "Connexion sur plusieurs nœuds : non",
  "Quels programmes Oracle ont été utilisés ?": "Programmes utilisés : PL/SQL, sqlplus, background processes",
  "A-t-on détecté du trafic réseau élevé ?": "Trafic réseau : faible (network wait time < 1s)",
  "Quels sont les hôtes les plus actifs ?": "Hôtes actifs : 1 (serveur unique)",

  // Statistiques
  "Quelle est la fréquence moyenne des requêtes ?": "Fréquence requêtes : ~63,347/h",
  "Combien d'événements sont enregistrés par jour ?": "Événements/jour : ~253,389 exécutions en 4h",
  "Quel est le taux de succès des requêtes ?": "Taux de succès : 100% (aucun échec détecté)",
  "Combien de sessions par utilisateur ?": "Sessions/utilisateur : SYS = 59 sessions",
  "Quel est le taux d’utilisation du buffer cache ?": "Buffer cache hit : 99.77%",
  "Quelle est la moyenne de sessions ouvertes ?": "Sessions ouvertes en moyenne : 57",
  "Quelles sont les opérations les plus fréquentes ?": "Opérations les plus fréquentes : SELECT",
  "Combien de requêtes ont été exécutées en 1h ?": "Requêtes exécutées par heure : ~63K",
  "Quelle est la variation de charge par jour ?": "Variation charge/jour : stable",
  "Combien d’objets ont été créés dans le mois ?": "Objets créés ce mois : non listés",

  // Analyse comportementale
  "Quels utilisateurs sont inactifs depuis longtemps ?": "Utilisateurs inactifs : SYSTEM, PDB$SEED (peu ou pas d'activité)",
  "Peut-on détecter des scripts automatisés ?": "Scripts automatisés : oui, exécution répétée de AWR_REPORT",
  "Des actions ont-elles été répétées anormalement ?": "Répétition anormale : non",
  "Peut-on identifier des patterns suspects dans les accès ?": "Patterns suspects : non détectés",
  "Quel utilisateur a lancé une séquence d’opérations anormale ?": "Séquence d’opérations anormales : aucune",
  "Peut-on prédire la charge demain ?": "Prédiction charge demain : charge faible probable",
  "Quels utilisateurs se connectent toujours au même moment ?": "Connexion toujours au même moment : SYS (nuit, 01:00–05:00)",
  "Y a-t-il des redondances dans les accès aux données ?": "Accès redondants : non observés",
  "Quelle session a fait des lectures mais aucun write ?": "Session avec lecture mais sans write : majorité des sessions",
  "Peut-on regrouper les sessions par comportement ?": "Sessions regroupées par comportement : toutes actives, majoritairement en lecture"
};